### ISSUE TITLE
parameter eps for FGM and IFGM

### ISSUE THREAD

**Issue by ZekunStevenZhang** [KaidiXu/StrAttack#1]
Hi, thanks for sharing this code.

I noticed that in the paper, you said you do a 10 FGM iteration as IFGM, and set the eps' for each iteration to eps/10. 

I'm wondering how you select eps. Is that the same one obtained by FGM grid search?

**Comment by KaidiXu** [comment]
Hi,

The eps for both FGM and IFGSM is 1e-3 which is the default setting in the code.

**Comment by ZekunStevenZhang** [comment]
Ok, Thanks a lot!
