### ISSUE TITLE
What is the version of tensorflow

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [KaidiXu/StrAttack#3]
Hi, thanks for sharing the code. 
I wonder what's the version of TensorFlow and keras?

**Comment by KaidiXu** [comment]
Hi Shuhuai,

It should be TF 1.12

Best,
Kaidi Xu
________________________________
From: Shuhuai Ren ***@***.***>
Sent: Saturday, April 3, 2021 5:05 AM
To: KaidiXu/StrAttack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KaidiXu/StrAttack] What is the version of tensorflow (#3)


Hi, thanks for sharing the code.
I wonder what's the version of TensorFlow?

**Comment by RenShuhuai-Andy** [comment]
thx
